# Generated by Django 3.2.8 on 2021-11-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='displayName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
