# Generated by Django 3.2.8 on 2021-11-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('friends', 'Friends Only'), ('send', 'Send to Author')], default='public', max_length=14),
        ),
    ]
