# Generated by Django 3.2.8 on 2021-11-26 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0002_user_displayname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='followrequest',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='ID',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ID',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
