# Generated by Django 3.2.8 on 2021-11-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0003_auto_20211125_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='published',
        ),
    ]
