# Generated by Django 3.2.8 on 2021-11-21 01:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0003_auto_20211120_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requesterId', models.CharField(max_length=100)),
                ('adresseeId', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=10)),
            ],
            options={
                'unique_together': {('requesterId', 'adresseeId')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='followrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='author',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='follower',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.DeleteModel(
            name='FollowRequest',
        ),
    ]
