# Generated by Django 3.2.8 on 2021-11-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0003_auto_20211125_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
