# Generated by Django 3.2.8 on 2021-11-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0004_rename_created_on_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends Only'), ('send', 'Send to Author')], default='PUBLIC', max_length=14),
        ),
    ]
