# Generated by Django 3.2.8 on 2021-11-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0004_alter_follower_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.CharField(max_length=200),
        ),
    ]
