# Generated by Django 3.2.8 on 2021-11-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0005_auto_20211126_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends Only'), ('SEND', 'Send to Author')], default='PUBLIC', max_length=14),
        ),
    ]
