# Generated by Django 3.2.8 on 2021-11-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0005_alter_follower_follower'),
        ('unhindled', '0007_auto_20211126_0538'),
    ]

    operations = [
    ]
