# Generated by Django 3.2.8 on 2021-12-03 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0009_auto_20211126_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('post', 'post'), ('like', 'like'), ('follow', 'follow'), ('comment', 'comment')], default='post', max_length=7)),
                ('link', models.URLField()),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('inbox_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_from', to=settings.AUTH_USER_MODEL)),
                ('inbox_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
