# Generated by Django 3.2.8 on 2021-12-04 00:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0009_auto_20211126_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
