# Generated by Django 3.2.8 on 2021-12-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0012_auto_20211203_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='inbox_from',
            field=models.CharField(max_length=200),
        ),
    ]
