# Generated by Django 3.2.8 on 2021-12-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0013_alter_inbox_inbox_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(default='https://unhindled.herokuapp.com/', editable=False, max_length=50),
        ),
    ]
