# Generated by Django 3.2.8 on 2021-12-04 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0015_auto_20211204_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='foreign_author',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(default='https://unhindled.herokuapp.com/', editable=False, max_length=50),
        ),
    ]
