# Generated by Django 3.2.8 on 2021-12-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0017_alter_post_send_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='send_to',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
