# Generated by Django 3.2.8 on 2021-12-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0017_alter_userprofile_profileimage'),
        ('unhindled', '0018_alter_post_send_to'),
    ]

    operations = [
    ]
