# Generated by Django 3.2.8 on 2021-12-06 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0019_merge_20211205_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignAuthor',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('host', models.CharField(max_length=200)),
                ('displayName', models.CharField(max_length=100)),
                ('github', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('profileImage', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='foreign_author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unhindled.foreignauthor'),
        ),
        migrations.AlterField(
            model_name='like',
            name='foreign_author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unhindled.foreignauthor'),
        ),
    ]
