# Generated by Django 3.2.8 on 2021-10-13 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('profileUrl', models.CharField(max_length=100)),
                ('githubUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contentType', models.CharField(choices=[('md', 'text/markdown'), ('txt', "text'plain"), ('png', 'image/png;base64'), ('jpeg', 'image/jpeg;base64')], max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unhindled.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('published', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unhindled.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unhindled.post')),
            ],
        ),
    ]
