# Generated by Django 3.2.8 on 2021-10-28 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('ID', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=100)),
                ('host', models.CharField(blank=True, max_length=100)),
                ('profileUrl', models.CharField(blank=True, max_length=100)),
                ('githubUrl', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='auth.user', verbose_name='user')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('more_info', models.TextField(blank=True, max_length=500)),
                ('photo', models.ImageField(blank=True, default='upload/profile_photos/default.png', upload_to='upload/profile_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contentType', models.CharField(choices=[('md', 'text/markdown'), ('txt', 'text/plain')], default=('txt', 'text/plain'), max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('send', 'Send to Author')], default=('public', 'Public'), max_length=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('send_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_to', to='unhindled.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('published', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unhindled.post')),
            ],
        ),
    ]
