# Generated by Django 3.1.6 on 2021-10-27 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=100)),
                ('host', models.CharField(blank=True, max_length=100)),
                ('profileUrl', models.CharField(blank=True, max_length=100)),
                ('githubUrl', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contentType', models.CharField(choices=[('md', 'text/markdown'), ('txt', 'text/plain')], default=('txt', 'text/plain'), max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default=('public', 'Public'), max_length=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedPost',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contentType', models.CharField(choices=[('md', 'text/markdown'), ('txt', 'text/plain')], default=('txt', 'text/plain'), max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default=('public', 'Public'), max_length=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('originalPostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_post', to='unhindled.post')),
                ('sharedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('published', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unhindled.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unhindled.post')),
            ],
        ),
    ]
