# Generated by Django 3.2.8 on 2021-10-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo',
            new_name='profileImage',
        ),
    ]
