# Generated by Django 3.2.8 on 2021-10-29 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='displayName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo',
            new_name='profileImage',
        ),
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('md', 'text/markdown'), ('txt', 'text/plain')], default=('md', 'text/markdown'), max_length=4),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='unhindled.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default=('pending', 'Pending'), max_length=10),
        ),
    ]
