# Generated by Django 3.1.6 on 2021-10-27 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unhindled', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='originalPost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unhindled.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='sharedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SharedPost',
        ),
    ]
