# Generated by Django 3.2.8 on 2021-10-28 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0002_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='send_to',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='ID',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='githubUrl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileUrl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('send', 'Send to Author')], default=('public', 'Public'), max_length=14),
        ),
    ]
