# Generated by Django 3.2.8 on 2021-10-29 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0002_alter_post_send_to'),
        ('unhindled', '0002_auto_20211028_1952'),
    ]

    operations = [
    ]
