# Generated by Django 3.2.8 on 2021-10-28 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unhindled', '0003_auto_20211027_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='send_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_to', to='unhindled.author'),
        ),
    ]
